sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
install:
  - npm install
git:
  submodules: false
deploy:
  provider: npm
  email: development@hive.pt
  api_key:
    secure: o0Ny1/E17ejn0FPeYcBmYlluzCmlm7I6F/wPbyeuCHgJB/KxN0UhMxyltvZ4GUpBPo8/H+cDRjZjvHQIE2ibPhKga877H2YHMRJLexogJ70tg8QkrC7h1aCVDLc14dQUjGZxZQayQGJF8J9T3sgZNvy2NqMSKTJEQYMdp/gH+JAfPebDk9BpkRFjap9Fy1KkWB1PcMGTSquZEHI2LFLte22Qdfpk7PhSeBffgvvLVIc6tOn7YSjv/RS1aZayr/sPoAaa5gnuxBaIummrz7uqKNqXwGWk6/J8EPdvk2L25T94bkMbL7u3sAAtSNg/MTSBjTRmmL6KCTzIkdG7c1pYf4aeRQfm2QHDblqQMC6J4ix3Z2V/2dOoFHithpuYd/wESiy5jWByWjO8I8oFEQOt4a1ntGU9Mdr4YPTHvAxWEqRcARGKr5O+cyzTQO8GwhRfC9NXnhgZ1/a0yzINYj4WkjhNMmMea9yf8Wqzdr0y4/XRcqpj6nv8ovXvgib2UmoB1dRU4ZxsfciT+viMOYWW3iPzUc36m0pHTQ+h2aoxAqCj512kGPGBvkEa8soNe6Fd9gAU1Y0G+/LM9uuWDo5M1ncuoPp03fmDUrY5ZL5aj4hFEyPYlvTe4da9qJpArRKJ5rnVQYbu0Vtl5lxpvFWRoWCS7BrY/sZgz0tyJ8Uz3wY=
  on:
    tags: true
    node_js: "8"
