sudo: false
dist: trusty
language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
install:
  - npm install
git:
  submodules: false
deploy:
  provider: npm
  email: development@hive.pt
  api_key:
    secure: I5icnL8tEQgz83fBikaF0675lBD4ZAN6pGGpsLg5Ye0ySGJiOrsL75kaT/y62juOlfT2Ym68MiqWUCqDDw7OzWXb7/mEFqGZMOgiAILKSgs8X3foyV8sQl7oExJbPtY1ZBeEUsh9Rf0FUEdibdTwaR8S804gLlnTCfCEUHJlfiK9/JcR2LlNA4fZzmWr85WW2pDE6QkU1kNKngeVepSrfVMoICUINYOcXoLiECL6gEkoKPtgWZuRwY0EDZngvIMV4e9HrlM+zKv/nHgPK1Y3FO/NojmZqi4ll01L+KP1gIgiISU82WOHqqdwKnxFyiCsVutva5x5dgoEXsMWG+oN6mZPRTjtV9sRAv6oWIswnccPp54PDhN2Ujxq2VSidfGN5pkrjsOS77U3ux8XeXIuo1VUkoZZ5f68F+PR/OP8uZQSk8ugW9uulaYmlujwD6kH//SKsWvQv81jMvhuKUnbsVf+KSOGu9nrSsBMh3X/ks3bE3EZWJfcBZr9SM8p6QfQX+YP9f7cNvNeP13BMzwa3QbqfoE55XJovj+finx49N5Zf2045tgT85p5NC5VmjtZC03VU/wVEZElnBOJZIODwQ2aLOfM5/YVVt4H3hOeMi2eB8cOMnjHZ1KqycDM6CeDMWn816ksbpVUHNjrhP99fsDExA6Df9jG1JNEDFWmMFg=
  on:
    tags: true
    node_js: "7"
