dist: trusty
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
install:
  - npm install
git:
  submodules: false
deploy:
  provider: npm
  email: development@hive.pt
  api_key:
    secure: Wc7JHIEHAtljGNdN5V9mRPsRr05blW8dQVRIJEuo/y5JgZqx5XCMieuFv4jbhp3NsoA6M0hhWV0OLB/3oZfMP1FR7pwwmhuaWsfqi2OmnbkS917fCtoEpNB/7YALj4SZKhdAJAWi7YS8OLBq1VWwAsX42gDAU4nS19YxVZxZdXYdxP1PiTJgXREBxE2YAx126vvhP+5aT9kLf/KPgt+cHfdKggYW1qdPRXdFRCKgtPwXIMUkm4YStK5RBL1gWwks2t1L9mtpot5rEhvJCD6kaNzkZIMb/GiB7deCK5qYly21lnZqpk0B002Yin+N1HUac0ti3P9/fCyqgy4eFCqmF18ldP8wqFFuAXzD0UpgGtIGzSLlJBST0cDOKJ5vOb5R7OocbHqKJwcPyJ40gCyjnLInLAMdWhCOzict2ySMzQ1g/yRWou12pu1ZRn20P+xbTK/V6C+GngaKd5KRI4xPyHsOs3sCDLmrlDMxApGTY4R4RN9wIRro9+xrGQk7ovR++J3jrRT44Z8xQwhppAHGW7KvSd/Vp2RNuatBrP+YS4rEFd3arTzXwuXD2cG5wJTLYF1qALg+HcTD1NnUL4lXrRJazEmHRgQsMjJMDZKNnR+aXj7k3jCKf7b9mSZlWk8wqhnU89Q5zncfCgD3+NaLgEdta9X0saN+nbFMYYGzztk=
  on:
    tags: true
    node_js: "8"
