sudo: false
dist: trusty
language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
install:
  - npm install
git:
  submodules: false
deploy:
  provider: npm
  email: development@hive.pt
  api_key:
    secure: OaEeyG+0L50D1JNa5EOg7I5Ix1ia0jujbt76SExCYiQ9DZ5KpppEGFnvuubr4xgc/mN49jLKR4gGSxCKQ2bvtPLjQE36sXuN08AE8OQLIb1z9icQixSZwbwyePvtrfdCmwxXn2Ea53wNCxx+IQdyPRQk5uMW4HRsGH6YOtTrCEijGxvCAUf9dDs2kbzA7C0aUGGoUyp5dERNpzTLP5zW29ACS5hfRc3ND008Ncxm2QWKcGHEBRAtASLxQdAZoZlmJsxhIkH8L6g8QEJ9tfwzn03adpUHs6x+a0kr2+/eYIAHajDDrLe/61CZXHUt0r7p+65qsVLllz9mW0XYz/L5B70H+oAaM+x5i3etjKtY/YaOA9VYxd+g/5dcJ9LJuVYpLkVQPr+Av9/QfyqpSER0X1I2FBZkx2LbMum09MP0Fkvs+oNdjMH+SgsB7xjn3GS4ybYBBVKiurPVHDNs43RsLpEr3a1kxaArmUlRA6DDum4Pejv62HM+qcTizEQhAuudfdh2gP4Ap4LBede9abiR8gVKScaVgG2QMmyJGi39h3eE849m3wjh5spno0vgsOi6iTMq4NLQn9HWadVXE+15KFrOP/95dWmsketM7FepptKWs+wyvjpVSy4WCajK5DP3Ahq9TEQBjIA4avsVGewBCboAFhbZokWGbg9ZWIIPbPg=
  on:
    tags: true
    node_js: "7"
